# Generated by Django 2.1 on 2020-04-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('form_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('positive_negative', models.CharField(choices=[('P', 'POSITIVE'), ('N', 'NEGATIVE')], max_length=1)),
            ],
        ),
    ]
